<a href="https://colab.research.google.com/github/YoungGreenP/Inha-young-code/blob/mains/Numpy%EA%B3%B5%EB%B6%801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 


In [ ]:
a= np.array([1,2,3])
print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
#list와 비교하기
L=[1,2,3]
A=np.array([1.,2.,3.])
print(L)
print(A)

[1, 2, 3]
[1. 2. 3.]


In [ ]:
A

array([1., 2., 3.])

In [ ]:
L

[1, 2, 3]

In [ ]:
for item in L:
  print(item)

1
2
3


In [ ]:
for item in A:
  print(item)

1.0
2.0
3.0


In [ ]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [ ]:
#바로 append가 안써짐
A=A.append(4)
print(A)

AttributeError: ignored

In [ ]:
A=np.append(A,4)
print(A)

[1. 2. 3. 4.]


In [ ]:
B=np.append(A,4)

In [ ]:
C=np.append(A,B)
print(C)

[1. 2. 3. 4. 1. 2. 3. 4. 4.]


In [ ]:
A=A+np.array([5])
print(A)

[6. 7. 8. 9.]


In [ ]:
#list 모든 원소를 2배로 만들기
L=[1,2,3]
L2=[]
for i in L:
  L2.append(i*2)
print(L2)

[2, 4, 6]


In [ ]:
#ndarray의 모든 원소를 2배로 만들기
A=np.array(L)
A2=A*2
print(A2)

[2 4 6]


In [ ]:
L*2

[1, 2, 3, 1, 2, 3]

In [ ]:
#리스트는 원소가 2배가 되는게 아니라 원소의 개수가 2배가 됨

In [ ]:
a=np.array([1,2,3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64


In [ ]:
b=np.asarray(a)
print(b)

[1 2 3]


In [ ]:
b[0]=9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [ ]:
c=np.array(a)
print(c)

[9 2 3]


In [ ]:
c[0]=1
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [ ]:
#3이 행 4가 열
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
b=np.ones((5,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
c=np.full((2,3),4)
print(c)

[[4 4 4]
 [4 4 4]]


In [ ]:
d=np.empty((3,3))
print(d)

[[1. 2. 3.]
 [4. 1. 2.]
 [3. 4. 4.]]


In [ ]:
e=np.zeros_like(a)
f=np.ones_like(a)
g=np.full_like(a,2)
h=np.empty_like(a)
print(e)
print(f)
print(g)
print(h)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
i=np.eye(3)
j=np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
k=np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# uniform distribution
l=np.random.rand(2,2)
print(l)

[[0.75067107 0.00957604]
 [0.5382351  0.81078978]]


In [ ]:
# normal distribution
m = np.random.randn(2,2)
print(m)

[[-0.13683141  0.35972053]
 [ 1.06598663 -0.61135273]]


In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3], dtype=np.float64)
c=np.array([1,2,3], dtype=np.int32)
print(a.dtype, b.dtype, c.dtype)

int64 float64 int32


In [ ]:
d=np.array([1,2,3], dtype='i1')
e=np.array([1,2,3], dtype='i2')
f=np.array([1,2,3], dtype='i4')
g=np.array([1,2,3], dtype='i8')
print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [ ]:
d=np.array([1,2,3], dtype='u1')
e=np.array([1,2,3], dtype='u2')
f=np.array([1,2,3], dtype='u4')
g=np.array([1,2,3], dtype='u8')
print(d.dtype, e.dtype, f.dtype, g.dtype)

uint8 uint16 uint32 uint64


In [ ]:
h=np.array([1,2,3], dtype='f2')
i=np.array([1,2,3], dtype='f4')
j=np.array([1,2,3], dtype='f8')
k=np.array([1,2,3], dtype='f16')
print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float128


4
